variables:
  GIT_DEPTH: 2

include:
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/python-pipeline-template'
    ref: dummy-pipeline
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/docker-pipeline-template'
    ref: dummy-pipeline
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/yaml-updater'
    ref: dummy-pipeline
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/repo-version-tagger'
    ref: main
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/changelog-validator'
    ref: main
    file: 'gitlab-ci.yml'

stages:
  - test-env
  - install
  - test
  - build-docker
  - container-scan
  - retag-docker
  - update-chart
  - version-tag
  - changelog-validate
