include:
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/get-envgonsul'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/docker-pipeline-template'
    ref: v1
    file: 'gcr.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/cloud-run-pipeline-template'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/repo-version-tagger'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/changelog-validator'
    ref: v1
    file: 'gitlab-ci.yml'

stages:
  - build-docker
  - container-scan
  - retag-docker
  - version-tag
  - deploy
  - changelog-validate
