variables:
  GIT_DEPTH: 2
  CHART_DIR: k8s/$CI_PROJECT_NAME

include:
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/docker-pipeline-template'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/yaml-updater'
    ref: v1
    file: 'gitlab-ci.yml' 
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/repo-version-tagger'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/changelog-validator'
    ref: v1
    file: 'gitlab-ci.yml'

stages:
  - build-docker
  - container-scan
  - retag-docker
  - update-chart
  - deploy
  - version-tag
  - changelog-validate

