include:
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/docker-pipeline-template'
    ref: v1
    file: 'gitlab-ci.yml'
stages:
  - build-docker
  - container-scan
  - retag-docker

build-docker:
  only:
    refs:
      - staging
      - master
      - /^hotfix/.+/
      - /^release/.+/