stages:
  - dependencies
  - test
  - build

dependencies:
  image: python:3.8.3-alpine
  stage: dependencies
  script:
    - ls
  artifacts:  
    paths:
      - /usr/local/lib/

lint:
  image: python:3.8.3-alpine
  stage: test
  script:
    - echo TODO
  cache:
    paths:
      - node_modules
    policy: pull

test:
  image: python:3.8.3-alpine
  stage: test
  script:
    - make tests
  allow_failure: true
  artifacts:  
    paths:
      - /usr/local/lib/

build:
  image: python:3.8.3-alpine
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist

