include:
  - project: 'yapo_team/yotf/sre-team/sre-services/git-ci-templates/docker-pipeline-template'
    ref: v1
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/golang-pipeline-template'
    ref: main
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/docker-pipeline-template'
    ref: gcr
    file: 'gitlab-ci.yml'
  - project: 'yapo_team/yotf/sre-team/sre-services/ci-templates/cloud-run-pipeline-template'
    ref: master
    file: 'gitlab-ci.yml'

stages:
  - build-docker
  - container-scan
  - retag-docker
  - deploy
