# File sourced from the GitLab template collection
include:
  - project: 'yapo_team/sandbox/engineering/pipelines/devops-templates'
    file: '.gitlab-ci-cloud-build.yml'

workflow:
  rules:
  - if: $CI_COMMIT_BRANCH == "develop"
    when: always
  - if: $CI_COMMIT_BRANCH == "staging"
    when: always
  - if: $CI_COMMIT_BRANCH == "master"
    when: always
  - when: never