language: python
dist: xenial

services:
  - docker

python:
  - 3.7-dev

env:
  global:
    - BRANCH=$([ ${TRAVIS_BRANCH} == master ] && echo latest || echo ${TRAVIS_BRANCH})

before_install:
  - configure_jfrog_client
  - helm init --client-only --stable-repo-url https://charts.helm.sh/stable

script:
  - make install
  - make tests
  - make build

after_success:
  - reports-publisher

after_failure:
  - reports-publisher

deploy:
  - provider: script
    script: make docker-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
  - provider: script
    script: make helm-publish
    on:
      all_branches: true
      condition: $TRAVIS_PULL_REQUEST = false
