# File: cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_PREFIX}${_NAME}', '.' ]
    # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/${_PREFIX}${_NAME}']
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['run', 'deploy', '${_PREFIX}${_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_PREFIX}${_NAME}', '--region', '${_REGION}', '--platform', 'managed']
options:
    substitution_option: 'ALLOW_LOOSE'
substitutions:
    _PREFIX: ''
    _NAME: ''
    _REGION: ''
