apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mkt-feeds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mkt-feeds.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mkt-feeds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mkt-feeds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: prom
              containerPort: 8877
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "{{ .Values.healthcheck.path }}"
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.healthcheck.path }}"
              port: http
            initialDelaySeconds: {{ .Values.healthcheck.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthcheck.readiness.periodSeconds }}
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: resource-mkt-feeds-db
                  key: HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: resource-mkt-feeds-db
                  key: PORT
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: resource-mkt-feeds-db
                  key: DB
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: resource-mkt-feeds-db
                  key: USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-mkt-feeds-db
                  key: PASS
            - name: SOURCEDATA_HOST
              valueFrom:
                secretKeyRef:
                  name: resource-external-blocketdb-slave
                  key: host
            - name: SOURCEDATA_PORT
              valueFrom:
                secretKeyRef:
                  name: resource-external-blocketdb-slave
                  key: port
            - name: SOURCEDATA_NAME
              valueFrom:
                secretKeyRef:
                  name: resource-external-blocketdb-slave
                  key: database
            - name: SOURCEDATA_USER
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: BNBI_USER
            - name: SOURCEDATA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: BNBI_PASS
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: AWS_STORAGE_BUCKET_NAME
            - name: AWS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: AWS_REGION_NAME
            - name: AWS_STORAGE_BUCKET_FOLDER
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: AWS_STORAGE_BUCKET_FOLDER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secret-mkt-feeds
                  key: AWS_ACCESS_KEY_ID
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/America/Santiago
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
