CREATE TABLE public.data_feed (
	ad_id text NULL PRIMARY KEY,
	ad_insertion text NULL,
	"name" text NULL,
	image_url text NULL,
	main_category text NULL,
	category text NULL,
	description text NULL,
	price text NULL,
	region text NULL,
	url text NULL,
	"condition" text NULL,
	ios_url text NULL,
	ios_app_store_id text NULL,
	ios_app_name text NULL,
	android_url text NULL,
	android_package text NULL,
	android_app_name text NULL,
	num_ad_replies text NULL
);